---
steps:
  - name: gcr.io/kaniko-project/executor:latest
    id: docker
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/service:${COMMIT_SHA}
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: flight
    waitFor: 
      - docker
    entrypoint: gcloud
    args:
      - run
      - deploy
      - flight
      - --execution-environment=gen2
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/service:${COMMIT_SHA}
      - --region=${_REGION}
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: hotel
    waitFor: 
      - docker
    entrypoint: gcloud
    args:
      - run
      - deploy
      - hotel
      - --execution-environment=gen2
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/service:${COMMIT_SHA}
      - --region=${_REGION}
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    waitFor:
      - flight
      - hotel
    entrypoint: sh
    args:
      - tcc-workflow.sh
substitutions:
  _REGION: us-central1
